@ECHO OFF

pushd %~dp0

REM Command file for Sphinx documentation

if "%SPHINXBUILD%" == "" (
	set SPHINXBUILD=sphinx-build
)
set SOURCEDIR=source
set BUILDDIR=build
if "%PORT%" == "" (
	set PORT=18182
)

REM Intercept leading environment variable flags (e.g. LATEXMKOPTS=...)
:parse_args
if "%~1"=="" goto check_sphinx
echo "%~1" | findstr /i /r "=" >nul
if errorlevel 1 (
	goto check_sphinx
) else (
	set %~1
	shift
	goto parse_args
)

:check_sphinx
%SPHINXBUILD% >NUL 2>NUL
if errorlevel 9009 (
	echo.
	echo.The 'sphinx-build' command was not found. Make sure you have Sphinx
	echo.installed, then set the SPHINXBUILD environment variable to point
	echo.to the full path of the 'sphinx-build' executable. Alternatively you
	echo.may add the Sphinx directory to PATH.
	echo.
	echo.If you don't have Sphinx installed, grab it from
	echo.https://www.sphinx-doc.org/
	exit /b 1
)

if "%1" == "" goto help

if /i "%1" == "help" goto help
if /i "%1" == "distclean" goto distclean
if /i "%1" == "deploy" goto deploy
if /i "%1" == "serve" goto serve

%SPHINXBUILD% -M %1 %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %O%
goto end

:distclean
echo.Cleaning up build and autogenerated directories...
if exist "%SOURCEDIR%\_autosummary" rmdir /s /q "%SOURCEDIR%\_autosummary"
if not exist "%BUILDDIR%" goto end
pushd "%BUILDDIR%"
for /d %%i in (*) do (
	if /i not "%%i" == "html" rmdir /s /q "%%i"
)
for %%i in (*) do del /q "%%i"
if exist "html" (
	pushd "html"
	for /d %%i in (*) do (
		echo %%i | findstr /i /r "^\.git" >nul
		if errorlevel 1 rmdir /s /q "%%i"
	)
	for %%i in (*) do (
		echo %%i | findstr /i /r "^\.git" >nul
		if errorlevel 1 del /q "%%i"
	)
	popd
)
popd
goto end

:deploy
echo.RSYNC is not natively available on Windows without Git Bash/WSL.
rsync -av --delete --no-p --no-g --chmod=ugo=rwX build/html/ engweb:/projects/engweb/eq1_pulse/
goto end

:serve
echo.Starting local web server on port %PORT%...
pushd build\html
python -m http.server %PORT%
popd
goto end

:help
%SPHINXBUILD% -M help %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %O%

:end
popd
